/**
 * @description home action types
 */
export const UPDATE_VIEWPORT = "UPDATE_VIEWPORT";
export const REQUEST_HOME_PAGE_DATA = "REQUEST_HOME_PAGE_DATA";
export const RECEIVE_HOME_PAGE_DATA = "RECEIVE_HOME_PAGE_DATA";
export const FAILURE_HOME_PAGE_DATA = "FAILURE_HOME_PAGE_DATA";
export const REQUEST_FILTERED_DATA = "REQUEST_FILTERED_DATA";
export const RECEIVE_FILTERED_DATA = "RECEIVE_FILTERED_DATA";
export const FAILURE_FILTERED_DATA = "FAILURE_FILTERED_DATA";
